"""rename anon to guest

Revision ID: 014e42bea4e7
Revises: 45c4c53c97e9
Create Date: 2025-12-23 20:44:03.847159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '014e42bea4e7'
down_revision = '45c4c53c97e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_key', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_key', 'scope', 'window_start', name='uq_guest_key_scope_window')
    )
    with op.batch_alter_table('guest_usage', schema=None) as batch_op:
        batch_op.create_index('idx_guest_window', ['window_start'], unique=False)
        batch_op.create_index('ix_guest_scope_window', ['scope', 'window_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_usage_guest_key'), ['guest_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_usage_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_usage_window_start'), ['window_start'], unique=False)

    with op.batch_alter_table('anon_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_anon_window')
        batch_op.drop_index('ix_anon_scope_window')
        batch_op.drop_index('ix_anon_usage_anon_key')
        batch_op.drop_index('ix_anon_usage_scope')
        batch_op.drop_index('ix_anon_usage_window_start')

    op.drop_table('anon_usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('anon_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='anon_usage_pkey'),
    sa.UniqueConstraint('anon_key', 'scope', 'window_start', name='uq_anon_key_scope_window', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('anon_usage', schema=None) as batch_op:
        batch_op.create_index('ix_anon_usage_window_start', ['window_start'], unique=False)
        batch_op.create_index('ix_anon_usage_scope', ['scope'], unique=False)
        batch_op.create_index('ix_anon_usage_anon_key', ['anon_key'], unique=False)
        batch_op.create_index('ix_anon_scope_window', ['scope', 'window_start'], unique=False)
        batch_op.create_index('idx_anon_window', ['window_start'], unique=False)

    with op.batch_alter_table('guest_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_usage_window_start'))
        batch_op.drop_index(batch_op.f('ix_guest_usage_scope'))
        batch_op.drop_index(batch_op.f('ix_guest_usage_guest_key'))
        batch_op.drop_index('ix_guest_scope_window')
        batch_op.drop_index('idx_guest_window')

    op.drop_table('guest_usage')
    # ### end Alembic commands ###
