"""add toss_payments_needs

Revision ID: 173c0f81b807
Revises: 148707ac5f25
Create Date: 2025-11-10 19:53:51.098897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '173c0f81b807'
down_revision = '148707ac5f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('billing_key', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('last4', sa.String(length=8), nullable=True),
    sa.Column('expiry_ym', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_key')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index('idx_pm_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_user_id'), ['user_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_webhook_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_received_at'), ['received_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('psp_transaction_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('failure_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('failure_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_index('idx_pay_created')
        batch_op.create_index('idx_pay_provider_txid', ['provider', 'psp_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_psp_transaction_id'), ['psp_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anchor_day', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('current_period_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('default_payment_method_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_sub_user_anchor', ['user_id', 'anchor_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_anchor_day'), ['anchor_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_current_period_end'), ['current_period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_current_period_start'), ['current_period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_default_payment_method_id'), ['default_payment_method_id'], unique=False)
        batch_op.create_foreign_key(None, 'payment_methods', ['default_payment_method_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscriptions_default_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_current_period_start'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_current_period_end'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_anchor_day'))
        batch_op.drop_index('idx_sub_user_anchor')
        batch_op.drop_column('default_payment_method_id')
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('current_period_start')
        batch_op.drop_column('anchor_day')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_payments_psp_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_idempotency_key'))
        batch_op.drop_index('idx_pay_provider_txid')
        batch_op.create_index('idx_pay_created', ['created_at'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('raw_response')
        batch_op.drop_column('raw_request')
        batch_op.drop_column('failure_message')
        batch_op.drop_column('failure_code')
        batch_op.drop_column('psp_transaction_id')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('order_id')
        batch_op.drop_column('provider')

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_processed_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_processed'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_updated_at'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_provider'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_created_at'))
        batch_op.drop_index('idx_pm_user_status')

    op.drop_table('payment_methods')
    # ### end Alembic commands ###
