"""add user_job, user_job_detail to users

Revision ID: 2f5470e8c6c9
Revises: f8c9d036aefd
Create Date: 2025-12-24 01:51:05.707650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5470e8c6c9'
down_revision = 'f8c9d036aefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.drop_column('user_job')
        batch_op.drop_column('user_job_detail')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_job', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('user_job_detail', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_job_detail')
        batch_op.drop_column('user_job')

    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_job_detail', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
