"""fix password_reset_token table

Revision ID: 2fc5da80e8dd
Revises: d65b9d761cb5
Create Date: 2025-11-08 17:55:40.119548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc5da80e8dd'
down_revision = 'd65b9d761cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_pk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('created_ua', sa.Text(), nullable=True))
        batch_op.drop_index('idx_prt_expires')
        batch_op.drop_index('idx_prt_user_created')
        batch_op.drop_index('ix_password_reset_tokens_user_id')
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_pk'), ['user_pk'], unique=False)
        batch_op.drop_constraint('password_reset_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_pk'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('used_ip')
        batch_op.drop_column('note')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('used_ip', sa.VARCHAR(length=48), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('password_reset_tokens_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_pk'))
        batch_op.create_index('ix_password_reset_tokens_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_prt_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_prt_expires', ['expires_at'], unique=False)
        batch_op.drop_column('created_ua')
        batch_op.drop_column('created_ip')
        batch_op.drop_column('user_pk')

    # ### end Alembic commands ###
