"""nicepay schema update

Revision ID: 45c4c53c97e9
Revises: 173c0f81b807
Create Date: 2025-12-14 02:25:36.992582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c4c53c97e9'
down_revision = '173c0f81b807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_tid', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last_auth_token', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('last_signature', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('last_order_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('card_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('card_name', sa.String(length=64), nullable=True))
        batch_op.create_index('idx_pm_provider_user', ['provider', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_card_code'), ['card_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_last_order_id'), ['last_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_tx_tid'), ['tx_tid'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_result_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('auth_result_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auth_token', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.String(length=64), nullable=True))
        batch_op.create_index('idx_pay_provider_order', ['provider', 'order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_auth_result_code'), ['auth_result_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_next_billing_at'), ['next_billing_at'], unique=False)

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=16), nullable=False))
        batch_op.create_index('idx_wh_provider_received', ['provider', 'received_at'], unique=False)
        batch_op.create_index('idx_wh_type_received', ['event_type', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_provider'))
        batch_op.drop_index('idx_wh_type_received')
        batch_op.drop_index('idx_wh_provider_received')
        batch_op.drop_column('provider')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_billing_at'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_client_id'))
        batch_op.drop_index(batch_op.f('ix_payments_auth_result_code'))
        batch_op.drop_index('idx_pay_provider_order')
        batch_op.drop_column('client_id')
        batch_op.drop_column('signature')
        batch_op.drop_column('auth_token')
        batch_op.drop_column('auth_result_message')
        batch_op.drop_column('auth_result_code')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_tx_tid'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_last_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_card_code'))
        batch_op.drop_index('idx_pm_provider_user')
        batch_op.drop_column('card_name')
        batch_op.drop_column('card_code')
        batch_op.drop_column('last_order_id')
        batch_op.drop_column('last_signature')
        batch_op.drop_column('last_auth_token')
        batch_op.drop_column('tx_tid')

    # ### end Alembic commands ###
