"""Expand anon_usage.anon_key to 255

Revision ID: 4ef263eafa64
Revises: c2bcef57d7ff
Create Date: 2025-11-02 17:50:48.247806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef263eafa64'
down_revision = 'c2bcef57d7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anon_usage', schema=None) as batch_op:
        batch_op.alter_column('anon_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anon_usage', schema=None) as batch_op:
        batch_op.alter_column('anon_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
