"""add display_name

Revision ID: 6930145329b6
Revises: 8cca03e6256b
Create Date: 2026-01-13 01:12:24.467812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6930145329b6'
down_revision = '8cca03e6256b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_display_name'), ['display_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_display_name'))
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
