"""add feedback admin_reply columns

Revision ID: 7c8c6e158ca7
Revises: 2fc5da80e8dd
Create Date: 2025-11-09 14:02:08.338856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8c6e158ca7'
down_revision = '2fc5da80e8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('replied_at')
        batch_op.drop_column('admin_reply')

    # ### end Alembic commands ###
