"""add oauth_identities

Revision ID: 8cca03e6256b
Revises: f630a33ae431
Create Date: 2026-01-13 00:58:38.667214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cca03e6256b'
down_revision = 'f630a33ae431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_identities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_sub', sa.String(length=255), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_sub', name='uq_oauth_provider_sub')
    )
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.create_index('idx_oauth_user_pk', ['user_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_identities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_identities_user_pk'), ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_identities_user_pk'))
        batch_op.drop_index(batch_op.f('ix_oauth_identities_created_at'))
        batch_op.drop_index('idx_oauth_user_pk')

    op.drop_table('oauth_identities')
    # ### end Alembic commands ###
