"""update Subscription

Revision ID: a60aeba279f2
Revises: 2f5470e8c6c9
Create Date: 2025-12-27 17:43:09.410904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60aeba279f2'
down_revision = '2f5470e8c6c9'
branch_labels = None
depends_on = None


def upgrade():
    # 1) 일단 NULL 허용으로 컬럼 추가 (기존 row 때문에 NOT NULL로 바로 추가하면 터짐)
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fail_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retry_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_at', sa.DateTime(), nullable=True))

    # 2) 기존 row 백필(Backfill)
    op.execute("UPDATE subscriptions SET cancel_at_period_end = FALSE WHERE cancel_at_period_end IS NULL")
    op.execute("UPDATE subscriptions SET fail_count = 0 WHERE fail_count IS NULL")

    # 3) NOT NULL 제약으로 확정
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('cancel_at_period_end', existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column('fail_count', existing_type=sa.Integer(), nullable=False)

        # 4) 인덱스 생성 (원래 자동생성되던 것 그대로)
        batch_op.create_index('idx_sub_retry', ['status', 'retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_cancel_at_period_end'), ['cancel_at_period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_fail_count'), ['fail_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_last_failed_at'), ['last_failed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_retry_at'), ['retry_at'], unique=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_retry_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_last_failed_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_fail_count'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_cancel_at_period_end'))
        batch_op.drop_index('idx_sub_retry')
        batch_op.drop_column('last_failed_at')
        batch_op.drop_column('retry_at')
        batch_op.drop_column('fail_count')
        batch_op.drop_column('cancel_at_period_end')

    # ### end Alembic commands ###
