"""init db

Revision ID: c2bcef57d7ff
Revises: 
Create Date: 2025-11-02 17:22:46.572236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2bcef57d7ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anon_key', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_key', 'window_start', name='uq_anon_key_window')
    )
    with op.batch_alter_table('anon_usage', schema=None) as batch_op:
        batch_op.create_index('idx_anon_window', ['window_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_anon_usage_anon_key'), ['anon_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_anon_usage_window_start'), ['window_start'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan_name', sa.String(length=64), nullable=False),
    sa.Column('plan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_sub_canceled', ['canceled_at'], unique=False)
        batch_op.create_index('idx_sub_created', ['created_at'], unique=False)
        batch_op.create_index('idx_sub_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_canceled_at'), ['canceled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('system_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_alerts_level'), ['level'], unique=False)

    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tier', 'window_start', name='uq_usage_user_tier_window')
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index('idx_usage_user_window', ['user_id', 'window_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_window_start'), ['window_start'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index('idx_visits_path_created', ['path', 'created_at'], unique=False)
        batch_op.create_index('idx_visits_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_pay_created', ['created_at'], unique=False)
        batch_op.create_index('idx_pay_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_pay_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('rewrite_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('honorific', sa.Boolean(), nullable=False),
    sa.Column('opener', sa.Boolean(), nullable=False),
    sa.Column('emoji', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rewrite_logs', schema=None) as batch_op:
        batch_op.create_index('idx_rewritelog_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_rewritelog_model_created', ['model_name', 'created_at'], unique=False)
        batch_op.create_index('idx_rewritelog_provider_created', ['provider', 'created_at'], unique=False)
        batch_op.create_index('idx_rewritelog_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rewrite_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rewrite_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rewrite_logs_user_pk'), ['user_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewrite_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rewrite_logs_user_pk'))
        batch_op.drop_index(batch_op.f('ix_rewrite_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_rewrite_logs_created_at'))
        batch_op.drop_index('idx_rewritelog_user_created')
        batch_op.drop_index('idx_rewritelog_provider_created')
        batch_op.drop_index('idx_rewritelog_model_created')
        batch_op.drop_index('idx_rewritelog_created_at')

    op.drop_table('rewrite_logs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index('idx_pay_user_created')
        batch_op.drop_index('idx_pay_status_created')
        batch_op.drop_index('idx_pay_created')

    op.drop_table('payments')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_user_id'))
        batch_op.drop_index(batch_op.f('ix_visits_path'))
        batch_op.drop_index(batch_op.f('ix_visits_created_at'))
        batch_op.drop_index('idx_visits_user_created')
        batch_op.drop_index('idx_visits_path_created')

    op.drop_table('visits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_created_at')

    op.drop_table('users')
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_window_start'))
        batch_op.drop_index(batch_op.f('ix_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_tier'))
        batch_op.drop_index('idx_usage_user_window')

    op.drop_table('usage')
    with op.batch_alter_table('system_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_alerts_level'))
        batch_op.drop_index(batch_op.f('ix_system_alerts_created_at'))

    op.drop_table('system_alerts')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_canceled_at'))
        batch_op.drop_index('idx_sub_status')
        batch_op.drop_index('idx_sub_created')
        batch_op.drop_index('idx_sub_canceled')

    op.drop_table('subscriptions')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))

    op.drop_table('feedback')
    with op.batch_alter_table('anon_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anon_usage_window_start'))
        batch_op.drop_index(batch_op.f('ix_anon_usage_anon_key'))
        batch_op.drop_index('idx_anon_window')

    op.drop_table('anon_usage')
    # ### end Alembic commands ###
