"""add user_templates

Revision ID: eaf29273c693
Revises: 4ef263eafa64
Create Date: 2025-11-03 13:43:29.955898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf29273c693'
down_revision = '4ef263eafa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('honorific', sa.Boolean(), nullable=False),
    sa.Column('opener', sa.Boolean(), nullable=False),
    sa.Column('emoji', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', name='uq_user_template_user_title')
    )
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.create_index('idx_user_templates_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_templates_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_templates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_templates_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_templates_created_at'))
        batch_op.drop_index('idx_user_templates_user_created')

    op.drop_table('user_templates')
    # ### end Alembic commands ###
