"""adding an account deletion schema to the user table

Revision ID: efb6abca2c90
Revises: a60aeba279f2
Create Date: 2026-01-02 07:46:21.145861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb6abca2c90'
down_revision = 'a60aeba279f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('purge_after', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('purge_after')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
