"""add ExtensionAuthCode, ExtensionToken

Revision ID: f630a33ae431
Revises: efb6abca2c90
Create Date: 2026-01-02 11:09:33.120632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f630a33ae431'
down_revision = 'efb6abca2c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_auth_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_auth_codes', schema=None) as batch_op:
        batch_op.create_index('idx_ext_code_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_ext_code_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_auth_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_extension_auth_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_auth_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_auth_codes_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_auth_codes_user_id'), ['user_id'], unique=False)

    op.create_table('extension_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_extension_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_extension_tokens_revoked', ['revoked_at'], unique=False)
        batch_op.create_index('idx_extension_tokens_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_last_used_at'), ['last_used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_extension_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_last_used_at'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_created_at'))
        batch_op.drop_index('idx_extension_tokens_user_id')
        batch_op.drop_index('idx_extension_tokens_revoked')
        batch_op.drop_index('idx_extension_tokens_expires_at')

    op.drop_table('extension_tokens')
    with op.batch_alter_table('extension_auth_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_auth_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_extension_auth_codes_used_at'))
        batch_op.drop_index(batch_op.f('ix_extension_auth_codes_expires_at'))
        batch_op.drop_index(batch_op.f('ix_extension_auth_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_extension_auth_codes_code'))
        batch_op.drop_index('idx_ext_code_user_created')
        batch_op.drop_index('idx_ext_code_expires')

    op.drop_table('extension_auth_codes')
    # ### end Alembic commands ###
