"""rename anon to guest

Revision ID: f8c9d036aefd
Revises: 014e42bea4e7
Create Date: 2025-12-24 01:49:34.245489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c9d036aefd'
down_revision = '014e42bea4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_job', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('user_job_detail', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.drop_column('user_job_detail')
        batch_op.drop_column('user_job')

    # ### end Alembic commands ###
